// import 'dart:developer' as developer;
import 'dart:io';
// import 'package:camera/camera.dart';
import 'package:d_button/d_button.dart';
import 'package:d_info/d_info.dart';
import 'package:d_session/d_session.dart';
import 'package:device_info_plus/device_info_plus.dart';
// import 'package:d_method/d_method.dart';
import 'package:flutter/material.dart';
// import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gap/gap.dart';
import 'package:intl/intl.dart';
// import 'package:geocoding/geocoding.dart';
// import 'package:geolocator/geolocator.dart';
// import 'package:google_fonts/google_fonts.dart';
import 'package:qms_application/common/common.dart';
import 'package:d_input/d_input.dart';
import 'package:qms_application/data/models/models.dart';
import 'package:qms_application/data/source/sources.dart';
// import 'package:qms_application/data/models/models.dart';
import 'package:qms_application/presentation/bloc/installation/installation_bloc.dart';
import 'package:qms_application/presentation/bloc/installation_records/installation_records_bloc.dart';
import 'package:qms_application/presentation/bloc/installation_records_username/installation_records_username_bloc.dart';
import 'package:qms_application/presentation/bloc/installation_step_records/installation_step_records_bloc.dart';
import 'package:qms_application/presentation/bloc/ticket_by_user/ticket_by_user_bloc.dart';
import 'package:qms_application/presentation/bloc/ticket_detail/ticket_detail_bloc.dart';
import 'package:qms_application/presentation/bloc/user/user_cubit.dart';
import 'package:qms_application/presentation/bloc/user_data/user_data_cubit.dart';
import 'package:qms_application/presentation/widgets/widgets.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart' as path_provider;
// import 'package:path_provider/path_provider.dart';
// import 'package:extended_image/extended_image.dart';

part 'login_page.dart';
part 'installation/dashboard_page.dart';
part 'main_page.dart';
part 'installation/installation_history.dart';
part 'inspection/inspection_history.dart';
part 'installation/installation_list_page.dart';
part 'installation/form_installation_page.dart';
part 'installation/detail_history_installation_page.dart';
part 'installation/summary_installation_page.dart';
part 'installation/detail_step_installation_page.dart';
part 'installation/dms_detail_ticket_page.dart';
part 'installation/environment_installation_page.dart';
part 'logout_page.dart';