import 'dart:developer' as developer;
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:d_button/d_button.dart';
import 'package:d_method/d_method.dart';
import 'package:flutter/material.dart';
// import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gap/gap.dart';
import 'package:geocoding/geocoding.dart';
import 'package:geolocator/geolocator.dart';
// import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:qms_application/common/common.dart';
import 'package:d_input/d_input.dart';
import 'package:qms_application/data/models/models.dart';
// import 'package:qms_application/data/models/models.dart';
// import 'package:qms_application/presentation/bloc/bloc/category_item_bloc.dart';
import 'package:qms_application/presentation/bloc/installation/installation_bloc.dart';
import 'package:qms_application/presentation/bloc/ticket_by_user/ticket_by_user_bloc.dart';
import 'package:qms_application/presentation/bloc/ticket_detail/ticket_detail_bloc.dart';
// import 'package:qms_application/presentation/bloc/ticket_detail/ticket_detail_bloc.dart';
import 'package:qms_application/presentation/widgets/widgets.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:permission_handler/permission_handler.dart';
// import 'package:path_provider/path_provider.dart';
// import 'package:extended_image/extended_image.dart';

part 'login_page.dart';
part 'dashboard_page.dart';
part 'main_page.dart';
part 'installation_history.dart';
part 'inspection_history.dart';
part 'installation_list_page.dart';
part 'form_installation_page.dart';
part 'detail_history_installation_page.dart';
// part 'installation_list_page_old.dart';
part 'camera_with_location_overlay.dart';
part 'summary_installation_page.dart';
part 'detail_step_installation_page.dart';
// part 'form_installation_page_old.dart';
// part 'form_installation_page_old_dinamis.dart';